{% set name = "pyquery" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 963e8d4e90262ff6d8dec072ea97285dc374a2f69cad7776f4082abcf6a1d8ae

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - lxml >=2.1
    - cssselect >=1.2.0

test:
  imports:
    - pyquery

about:
  home: https://github.com/gawel/pyquery
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A jquery-like library for python
  description: |
    pyquery allows you to make jquery queries on xml documents. The API is as
    much as possible the similar to jquery. pyquery uses lxml for fast xml
    and html manipulation.
  doc_url: http://pyquery.rtfd.org
  dev_url: https://github.com/gawel/pyquery

extra:
  recipe-maintainers:
    - nehaljwani
