{% set name = "pyquery" %}
{% set version = "1.4.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4771db76bd14352eba006463656aef990a0147a0eeaf094725097acfa90442bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_value }}

build:
  noarch: python
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - lxml >=2.1
    - cssselect >0.7.9

test:
  imports:
    - pyquery

about:
  home: https://github.com/gawel/pyquery
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A jquery-like library for python
  description: |
      pyquery allows you to make jquery queries on xml documents. The API is as
      much as possible the similar to jquery. pyquery uses lxml for fast xml
      and html manipulation.
  doc_url: http://pyquery.rtfd.org
  dev_url: https://github.com/gawel/pyquery

extra:
  recipe-maintainers:
    - nehaljwani
