travis:
  secure:
    BINSTAR_TOKEN: RNc8mEpO3KRJtmoSgb3jwVzkC/ypODk4QrC3bpLjJ75Nf3ObfwWaRA7Vz3GVmlkjoyBt7QL16pdM58KIwaiWMLSvGkw+vG1NHTRMYGdwCnYg5TFKwkbvBR/2auIGW1+4QX68IRxj/y2V3reqhF88HCCg++f2wMwl+UvDM+aIxXxCn5+aWDhhDf/KLysEpNotwMWlPkumLEnUXXRx8jNqKnofe7PDC4uP6xQGK4Ut47kvMJxNr7+rlJ5J+HvuTH3PBSmyO1jpEWAjlxRbscXIeypCav2Nwx0JClp+U3jFLbYKt7caydkuCuv3cGXvSTYwpbM1Ocif07o36VkJm1XRWhtG1rwoj7HcpYTTTO9kJ+Q6RppTICHw31l06Wm/xKpwDx9gI8O5a+cmdG966i8PBykGwZNc0e7Xhl9hVv2Wgv9NnWUUgRl623C/O23+OB3xoxJ9trfnwkKjX5UJoWA2At4ETRPiWXwl8Flvbk0G0G+Nq1I4OK7QoiQSBQ0x7/CruAnyssMK/AycLadLBGQDCIXyEk6YLqe0N1Yb5r6Z3PjYjbPKSaj+i8cyDB41WKahlJyu6CMQHWoHMJG5yxwpalGzuDMNZGa9zwBkY+tAggS/UetxpIOLF+3oo2SHu9xj0scq/NiJLaReK6CSCfvpwFXUfbH8CGjWpfE5A5E8z00=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
